### PR TITLE
feature/complex conjugate

### PR DESCRIPTION
**Pull request by jkdufair**
Expose the sympy `conjugate` function. That's about it.

### CODE REVIEW

**Comment by jkdufair** [comment]
Ready! This update exposes the sympy 'conjugate' function as 'conj'

**Comment by jkdufair** [comment]
Web update: https://gitlab.com/purdue-informatics/variate/variate-web/-/merge_requests/1616  
Solution engine update: https://gitlab.com/purdue-informatics/variate/variate-solution-engine/-/merge_requests/198

**Comment by tragessere** [comment]
@jkdufair I had to build this for WSL to get the parser updates, would you like me to go ahead and push the changes for /lib/linux/latex2antlrJson.so?

**Comment by tragessere** [comment]
> @jkdufair I had to build this for WSL to get the parser updates, would you like me to go ahead and push the changes for /lib/linux/latex2antlrJson.so?

Actually I do see some commits where you changed it, but it doesn't seem to be in the final list of changed files. Maybe the original version got pushed back in by accident?

**Comment by jkdufair** [comment]
> > @jkdufair I had to build this for WSL to get the parser updates, would you like me to go ahead and push the changes for /lib/linux/latex2antlrJson.so?
> 
> Actually I do see some commits where you changed it, but it doesn't seem to be in the final list of changed files. Maybe the original version got pushed back in by accident?

@tragessere Well what the heck. Oddly, that directory is in .gitignore. For good reason, I suppose. If you want to push that file, that would be great. Thank you.

**Review by tragessere — APPROVED** [review]

**Review by lane174 — APPROVED** [review]
Looks good here as well.

**Pull request merged**
