### PR TITLE
Add more trig tests

### PR DESCRIPTION
**Pull request by lily514**
No logic changes, just adding some tests

### CODE REVIEW

**Comment by jkdufair** [comment]
Looks great and tests pass!

**Review by builtbywill — APPROVED** [review]

**Comment by lily514** [comment]
@builtbywill @jkdufair after I merge this to develop should I release it to master, or should we wait since it doesn't add anything besides test cases?

**Comment by jkdufair** [comment]
> @builtbywill @jkdufair after I merge this to develop should I release it to master, or should we wait since it doesn't add anything besides test cases?

I think master is fine. No reason not to that I can think of.

**Comment by builtbywill** [comment]
> @builtbywill @jkdufair after I merge this to develop should I release it to master, or should we wait since it doesn't add anything besides test cases?

@lily514 yeah seems fine to merge it all together to me

**Pull request merged**
